In [33]:
import numpy as np

In [34]:
import pandas as pd
import sklearn as skl
import matplotlib.pyplot as plt

In [35]:
dt = pd.read_csv(r"C:\IMP COLLEGS THINGS\Final Year\Seventh Sem\Major project\banana_spectral_dataset.csv")
dt

,timestamp,date,elapsed_seconds,banana_id,session_id,sample_no,capture_mode,F1_405,F2_425,FZ_450,...,F4_515,F5_550,FY_555,FXL_600,F6_640,F7_690,F8_745,NIR_855,Status,Days remaining
0,13-10-2026 15:33,13-10-26,0.28,1,20261013_153332,1,continuous,21,65,264,...,720,379,1346,1324,1155,684,99,50,raw,2
1,13-10-2026 15:34,13-10-26,60.57,1,20261013_153332,2,continuous,21,65,264,...,720,379,1345,1323,1155,684,99,50,raw,2
2,13-10-2026 15:35,13-10-26,120.85,1,20261013_153332,3,continuous,21,65,264,...,720,379,1345,1323,1155,684,99,50,raw,2
3,13-10-2026 15:36,13-10-26,181.15,1,20261013_153332,4,continuous,21,65,264,...,720,379,1345,1323,1154,684,99,50,raw,2
4,13-10-2026 15:37,13-10-26,241.44,1,20261013_153332,5,continuous,21,65,265,...,720,379,1345,1323,1155,684,99,50,raw,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
509,2026-10-23T18:39:13,23-10-26,9605.19,4,20261023_155908,17,continuous,1,4,18,...,37,19,70,73,74,46,6,3,Riped,0
510,2026-10-23T18:49:14,23-10-26,10205.49,4,20261023_155908,18,continuous,1,4,18,...,37,19,70,73,74,46,7,3,Riped,0
511,2026-10-23T18:59:14,23-10-26,10805.80,4,20261023_155908,19,continuous,1,4,19,...,37,19,70,73,74,46,7,3,Riped,0
512,2026-10-23T19:09:14,23-10-26,11406.09,4,20261023_155908,20,continuous,1,4,18,...,37,19,69,73,74,46,7,3,Riped,0
513,2026-10-23T19:19:15,23-10-26,12006.39,4,20261023_155908,21,continuous,1,4,18,...,37,19,69,73,74,46,6,3,Riped,0

In [36]:
dt1 = dt.drop(['date', 'elapsed_seconds', 'session_id', 'sample_no', 'capture_mode', 'timestamp', 'banana_id'], axis='columns')
dt1

,F1_405,F2_425,FZ_450,F3_475,F4_515,F5_550,FY_555,FXL_600,F6_640,F7_690,F8_745,NIR_855,Status,Days remaining
0,21,65,264,283,720,379,1346,1324,1155,684,99,50,raw,2
1,21,65,264,283,720,379,1345,1323,1155,684,99,50,raw,2
2,21,65,264,283,720,379,1345,1323,1155,684,99,50,raw,2
3,21,65,264,283,720,379,1345,1323,1154,684,99,50,raw,2
4,21,65,265,283,720,379,1345,1323,1155,684,99,50,raw,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
509,1,4,18,20,37,19,70,73,74,46,6,3,Riped,0
510,1,4,18,20,37,19,70,73,74,46,7,3,Riped,0
511,1,4,19,20,37,19,70,73,74,46,7,3,Riped,0
512,1,4,18,20,37,19,69,73,74,46,7,3,Riped,0
513,1,4,18,20,37,19,69,73,74,46,6,3,Riped,0

In [37]:
dt1["Status_clean"] = (
    dt1["Status"]
    .str.strip()
    .str.lower()
    .replace({
        "raw": "RAW",
        "ripe": "RIPE",
        "riped": "RIPE",
        "slightly riped": "SLIGHTLY RIPED",
        "overripe": "OVERRIPE"
    })
)

# Check the cleaned labels
print("Cleaned label counts:\n")
print(dt1["Status_clean"].value_counts())

print("\nNumber of unique labels:", dt1["Status_clean"].nunique())

Cleaned label counts:

Status_clean
RAW               191
RIPE              180
OVERRIPE          100
SLIGHTLY RIPED     43
Name: count, dtype: int64

Number of unique labels: 4

In [38]:
dummies = pd.get_dummies(dt1.Status_clean, dtype=int)
dummies

     OVERRIPE  RAW  RIPE  SLIGHTLY RIPED
0           0    1     0               0
1           0    1     0               0
2           0    1     0               0
3           0    1     0               0
4           0    1     0               0
..        ...  ...   ...             ...
509         0    0     1               0
510         0    0     1               0
511         0    0     1               0
512         0    0     1               0
513         0    0     1               0

[514 rows x 4 columns]

In [39]:
final = pd.concat([dt1, dummies], axis='columns')
final

,F1_405,F2_425,FZ_450,F3_475,F4_515,F5_550,FY_555,FXL_600,F6_640,F7_690,F8_745,NIR_855,Status,Days remaining,Status_clean,OVERRIPE,RAW,RIPE,SLIGHTLY RIPED
0,21,65,264,283,720,379,1346,1324,1155,684,99,50,raw,2,RAW,0,1,0,0
1,21,65,264,283,720,379,1345,1323,1155,684,99,50,raw,2,RAW,0,1,0,0
2,21,65,264,283,720,379,1345,1323,1155,684,99,50,raw,2,RAW,0,1,0,0
3,21,65,264,283,720,379,1345,1323,1154,684,99,50,raw,2,RAW,0,1,0,0
4,21,65,265,283,720,379,1345,1323,1155,684,99,50,raw,2,RAW,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
509,1,4,18,20,37,19,70,73,74,46,6,3,Riped,0,RIPE,0,0,1,0
510,1,4,18,20,37,19,70,73,74,46,7,3,Riped,0,RIPE,0,0,1,0
511,1,4,19,20,37,19,70,73,74,46,7,3,Riped,0,RIPE,0,0,1,0
512,1,4,18,20,37,19,69,73,74,46,7,3,Riped,0,RIPE,0,0,1,0
513,1,4,18,20,37,19,69,73,74,46,6,3,Riped,0,RIPE,0,0,1,0

In [40]:
final1 = final.drop(['Status_clean', 'SLIGHTLY RIPED', 'Status'], axis='columns')
final1

,F1_405,F2_425,FZ_450,F3_475,F4_515,F5_550,FY_555,FXL_600,F6_640,F7_690,F8_745,NIR_855,Days remaining,OVERRIPE,RAW,RIPE
0,21,65,264,283,720,379,1346,1324,1155,684,99,50,2,0,1,0
1,21,65,264,283,720,379,1345,1323,1155,684,99,50,2,0,1,0
2,21,65,264,283,720,379,1345,1323,1155,684,99,50,2,0,1,0
3,21,65,264,283,720,379,1345,1323,1154,684,99,50,2,0,1,0
4,21,65,265,283,720,379,1345,1323,1155,684,99,50,2,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
509,1,4,18,20,37,19,70,73,74,46,6,3,0,0,0,1
510,1,4,18,20,37,19,70,73,74,46,7,3,0,0,0,1
511,1,4,19,20,37,19,70,73,74,46,7,3,0,0,0,1
512,1,4,18,20,37,19,69,73,74,46,7,3,0,0,0,1
513,1,4,18,20,37,19,69,73,74,46,6,3,0,0,0,1

In [41]:
from sklearn.model_selection import train_test_split
X = final1.drop(['Days remaining'], axis='columns')
X

,F1_405,F2_425,FZ_450,F3_475,F4_515,F5_550,FY_555,FXL_600,F6_640,F7_690,F8_745,NIR_855,OVERRIPE,RAW,RIPE
0,21,65,264,283,720,379,1346,1324,1155,684,99,50,0,1,0
1,21,65,264,283,720,379,1345,1323,1155,684,99,50,0,1,0
2,21,65,264,283,720,379,1345,1323,1155,684,99,50,0,1,0
3,21,65,264,283,720,379,1345,1323,1154,684,99,50,0,1,0
4,21,65,265,283,720,379,1345,1323,1155,684,99,50,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
509,1,4,18,20,37,19,70,73,74,46,6,3,0,0,1
510,1,4,18,20,37,19,70,73,74,46,7,3,0,0,1
511,1,4,19,20,37,19,70,73,74,46,7,3,0,0,1
512,1,4,18,20,37,19,69,73,74,46,7,3,0,0,1
513,1,4,18,20,37,19,69,73,74,46,6,3,0,0,1

In [42]:
y = final1['Days remaining']
y

0      2
1      2
2      2
3      2
4      2
      ..
509    0
510    0
511    0
512    0
513    0
Name: Days remaining, Length: 514, dtype: int64

In [48]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [49]:
from sklearn.ensemble import RandomForestClassifier

Model1 = RandomForestClassifier(n_estimators=100, random_state=42)
Model1.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [50]:
from sklearn.linear_model import LogisticRegression

Model2 = LogisticRegression(max_iter=1000)
Model2.fit(X_train, y_train)

c:\Users\nimis\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

In [51]:
import xgboost as xgb

Model3 = xgb.XGBClassifier(
    n_estimators=100, 
    learning_rate=0.1, 
    max_depth=5, 
    tree_method="hist", 
    random_state=42
)
Model3.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.1, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=100,
              n_jobs=None, num_parallel_tree=None, ...)

In [52]:
from sklearn import tree

Model4 = tree.DecisionTreeClassifier()
Model4.fit(X_train, y_train)

DecisionTreeClassifier()

In [53]:
from sklearn.linear_model import LinearRegression

Model5 = LinearRegression()
Model5.fit(X_train, y_train)

LinearRegression()

In [54]:
#Sample 1 Predictions
Prediction1 = Model1.predict([[16, 54, 219, 232, 615, 332, 1148, 1105, 972, 550, 90, 44, 0, 0, 0]])
Prediction2 = Model2.predict([[16, 54, 219, 232, 615, 332, 1148, 1105, 972, 550, 90, 44, 0, 0, 0]])
Prediction3 = Model3.predict([[16, 54, 219, 232, 615, 332, 1148, 1105, 972, 550, 90, 44, 0, 0, 0]])
Prediction4 = Model4.predict([[16, 54, 219, 232, 615, 332, 1148, 1105, 972, 550, 90, 44, 0, 0, 0]])
Prediction5 = Model5.predict([[16, 54, 219, 232, 615, 332, 1148, 1105, 972, 550, 90, 44, 0, 0, 0]]) 
#Sample 2 Predictions
Prediction6 = Model1.predict([[26, 86, 317, 320, 796, 425, 1477, 1429, 1329, 746, 108, 62, 0, 0, 0]])
Prediction7 = Model2.predict([[26, 86, 317, 320, 796, 425, 1477, 1429, 1329, 746, 108, 62, 0, 0, 0]])
Prediction8 = Model3.predict([[26, 86, 317, 320, 796, 425, 1477, 1429, 1329, 746, 108, 62, 0, 0, 0]])
Prediction9 = Model4.predict([[26, 86, 317, 320, 796, 425, 1477, 1429, 1329, 746, 108, 62, 0, 0, 0]])
Prediction10 = Model5.predict([[26, 86, 317, 320, 796, 425, 1477, 1429, 1329, 746, 108, 62, 0, 0, 0]])

print("Predictions for Sample 1:")
print("Random Forest Prediction:", Prediction1)
print("Logistic Regression Prediction:", Prediction2)
print("XGBoost Prediction:", Prediction3)       
print("Decision Tree Prediction:", Prediction4)
print("Linear Regression Prediction:", Prediction5)
print("\nPredictions for Sample 2:")
print("Random Forest Prediction:", Prediction6)
print("Logistic Regression Prediction:", Prediction7)
print("XGBoost Prediction:", Prediction8)
print("Decision Tree Prediction:", Prediction9)
print("Linear Regression Prediction:", Prediction10)

Predictions for Sample 1:
Random Forest Prediction: [0]
Logistic Regression Prediction: [2]
XGBoost Prediction: [0]
Decision Tree Prediction: [0]
Linear Regression Prediction: [2.8450952]

Predictions for Sample 2:
Random Forest Prediction: [2]
Logistic Regression Prediction: [2]
XGBoost Prediction: [0]
Decision Tree Prediction: [0]
Linear Regression Prediction: [5.85617754]

c:\Users\nimis\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
c:\Users\nimis\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
c:\Users\nimis\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\nimis\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
c:\Users\nimis\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
c:\Users\nimis\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
c:\Users\nimis\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\nimis\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(